### PR TITLE
Bump version, re-render with smithy

### PR DESCRIPTION
**Pull request by guillochon**

### CODE REVIEW

**Comment by guillochon** [comment]
So I'm not sure why the CircleCI is failing here, it's emitting a `1` exit code at the end, but I see no obvious errors in the build. Any ideas @ocefpaf?

**Comment by ocefpaf** [comment]
No idea. It seems that you are running quite a long test there! (I re-started it earlier to see if things would solve themselves but the build never ended!!)

Try building it locally to debug this. (See http://conda-forge.github.io/docs/testing.html#run-docker-tests-locally-for-feedstock for more info.)

**Comment by guillochon** [comment]
I think you are right @ocefpaf about the run time, the tests are ~25 minutes per Python version which means 3x25 = 75 minutes, too long. I'll reduce the test length.

**Comment by pkgw** [comment]
OK, I believe I understand why Circle CI is failing.

*Context:* this is a weird bug because the first `conda build` command in the CI appears to succeed by all visible manifestations, but for some reason the script that executes the build exits prematurely. That script is a "here-file" that is piped into a `docker run` command in the script [ci_support/run_docker_build.sh](https://github.com/conda-forge/mosfit-feedstock/blob/master/ci_support/run_docker_build.sh#L64). After that first `conda build` command, it seems that the docker-ified bash program just exits instantly, without an error code.

*Short answer:* this is another manifestation of the `mpich` bug where its version of the `mpirun` command exits and leaves its output streams in nonblocking mode ([mpich bug](http://trac.mpich.org/projects/mpich/ticket/1782), [relevant StackOverflow Q&A](http://stackoverflow.com/a/43700228/3760486)).

*Analysis:* If I reduce the `test.sh` script to just call `mpirun -np 2 echo hello`, the same problem surfaces, and I have verified that the stdout of the Docker bash program is left in nonblocking mode. I have done a variety of tests and I cannot see a not-weird way to get that bash process to abort early without leaving some piece of evidence about what problem it ran into, therefore I conclude that it must be aborting early for a weird reason.

*Conclusive evidence:* I ran a shortened version of the `test.sh` script that ran the first mosfit test in the usual way in a local Docker environment. I was able to reproduce the inexplicable failure. I then edited this script to hook up the `mpirun` command's standard file descriptors to disconnect them from those used by the `bash` shell: `mpirun ... </dev/null 2>&1 |cat`. This version ran the full build script as normal.

*Suggested solutions:* 1. Do not use `mpirun` for any mosfit tests on Circle CI. 2. Use `mpirun`, but pipe its inputs and outputs as described above so that it cannot monkey with the blocking-ness of its calling shell's file descriptors. 3. Bonus idea: maybe mosfit should provide a tiny wrapper script that calls `mpirun` with the input rerouting described above, to make it easier to avoid this stuff until mpich is fixed.

CC @minrk @dalcinl as a heads-up in case you happen to get weird CI failures on Circle when building packages related to `mpich`.

**Comment by pkgw** [comment]
Superseded by #3.

**Pull request closed without merging**
