### PR TITLE
Update to version 1.2

### PR DESCRIPTION
**Pull request by pkgw**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Also adding @gmzsebastian as a maintainer.

In my local testing, the tests didn't pass — not sure whether it's a problem that can be fixed here or represents something that ought to be dealt with upstream. We'll see if the same errors appear in the cloud CI.

### CODE REVIEW

**Comment by pkgw** [comment]
OK, the CI here is showing the same error I saw locally. Basically, inside the package test script:

```
Copying MOSFiT folder hierarchy to current working directory (disable with `--no-copy-at-launch`).
Event `SN2009do` interpreted as a transient name, downloading lists of transient aliases...
Warning: Could not download `OSC` names (are you online?), using cached list.
Warning: Could not download `OTC` names (are you online?), using cached list.
Warning: Could not download `OKC` names (are you online?), using cached list.
Warning: Could not read list of OSC names!
Warning: Could not read list of OTC names!
Warning: Could not read list of OKC names!
Traceback (most recent call last):
  File "$PREFIX/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "$PREFIX/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "$PREFIX/lib/python3.10/site-packages/mosfit/__main__.py", line 5, in <module>
    main.main()
  File "$PREFIX/lib/python3.10/site-packages/mosfit/main.py", line 985, in main
    Fitter(**fitargs).fit_events(**fitargs)
  File "$PREFIX/lib/python3.10/site-packages/mosfit/fitter.py", line 311, in fit_events
    fetched_events = self._fetcher.fetch(
  File "$PREFIX/lib/python3.10/site-packages/mosfit/fetcher.py", line 145, in fetch
    for name in self._names[catalog]:
KeyError: 'OSC'
```

@conda-forge/mosfit team, do any of you know whether this indicates an issue in how the CI is set up, or potentially a bug in MoSFIT itself?

Relatedly, I believe that the CI test environments should have network access, so I'm not sure why the "Could not download" errors are happening.

**Comment by mnicholl** [comment]
Hi Peter, I think I know why this gives an error and I don’t think it's a problem with conda or Mosfit — it reflects the current non-functioning of the Open Astronomy Catalogs where it’s trying to get the data to fit.

It would be good to keep this fetcher class in case those catalogs are ever restored, but probably we should remove any test cases that try to use it!

I can edit the tests to only use local data, should I then do another release (1.2.1)?

**Comment by pkgw** [comment]
@mnicholl The tests that we're running are custom ones stored in this feedstock repository, so a new release may not be necessary. See the [forge_test.sh][1] file. Is there a different sample event that would avoid the issue?

[1]: https://github.com/conda-forge/mosfit-feedstock/blob/main/recipe/forge_test.sh

That being said, the earlier message does say "Could not download `OSC` names (are you online?), using cached list.", which makes me think that it should fail a little bit more gracefully than the `KeyError` error.

**Comment by mnicholl** [comment]
Ah ok! If you replace SN2009do and SN2007bg in forge_test.sh with the local files:

MOSFiT/mosfit/tests/LSQ12dlf.json
MOSFiT/mosfit/tests/SN2006le.json

That should hopefully solve the issue. Though I agree that error message is a bit misleading

**Comment by pkgw** [comment]
OK, I've pushed an update that should hopefully help with the tests. Turns out there is already a `source_files:` statement in the `test` section of the `meta.yaml` that helps make this work.

Locally the MPI test seems to run into the issue https://github.com/adrn/schwimmbad/issues/32 :

```
Traceback (most recent call last):
  File "$PREFIX/lib/python3.10/site-packages/schwimmbad/mpi.py", line 73, in __init__
    self.wait()
  File "$PREFIX/lib/python3.10/site-packages/schwimmbad/mpi.py", line 120, in wait
    func, arg = task
ValueError: not enough values to unpack (expected 2, got 1)
```

... but it looks like MoSFIT swallows the error such that the test suite still passes. Based on the age of that report, this issue appears to have been around for a long time, so I don't think this should hold up the package update.

**Comment by pkgw** [comment]
Confirmed that the MPI test in the CI runs into the same schwimmbad issue; James identified it as having to do with incompatibility with mpi4py >= 3.0. It might be easy to fix in schwimmbad; mpi4py 3 has been out for nearly seven years, FWIW, so I don't think it makes sense to constrain us to use the 2.x series or anything.

**Pull request merged**
