### PR TITLE
Bump to 1.0.1

### PR DESCRIPTION
**Pull request by guillochon**

### CODE REVIEW

**Comment by guillochon** [comment]
Hi @ocefpaf, two problems with this PR in the Windows build that I was hoping to get some help with:

1. It looks like `noarch` isn't working for this package because there's a named executable that points to the Python module (users can just run `mosfit ...` on the command line). This is causing the failure in Python 3.5.
2. For Python 2.7/3.6 it looks like `conda` is being downgraded for some reason, then the batch file can't be found.

Any thoughts on either issue?

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> 1. It looks like `noarch` isn't working for this package because there's a named executable that points to the Python module (users can just run `mosfit ...` on the command line). This is causing the failure in Python 3.5.

Let's remove it then.

> 2. For Python 2.7/3.6 it looks like `conda` is being downgraded for some reason, then the batch file can't be found.

That will be corrected by the re-rendering I did above.

**Comment by guillochon** [comment]
Closing in favor of the 1.0.2 bump.

**Pull request closed without merging**
